name: Next.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Ensures clean install (faster & stricter than npm install)

      - name: Lint code
        run: npm run lint  # Ensures no ESLint issues

      - name: Type check (Strict TypeScript)
        run: npm run type-check # Add "type-check" script in package.json for "tsc --noEmit"

      - name: Run tests
        run: npm test  # Ensures all tests pass

      - name: Build project
        run: npm run build  # Ensures production build works

      - name: Deploy (Optional)
        if: success()
        run: echo "Deploying..." # Replace with actual deploy script (e.g., Vercel, Railway)
